### ISSUE TITLE
Update chef_handler dependency to remove pessimistic version constraint?

### ISSUE THREAD

**Issue by hydrant25** [DataDog/chef-datadog#270]
I'm wondering if it's possible to remove the version constraint on `chef_handler` `~> 1.1.0` from this cookbook so that it pulls in the latest, v1.2.0? 

In my chef-repo, I believe this constraint, when combined with other community cookbook constraints, is causing berkshelf to resolve to using `datadog` cookbook version v0.1.2 along with `chef_handler` v1.2.0. I believe v0.1.2 was the last release the `datadog` cookbook had just a >= constraint on `chef_handler`.

Or, could we update the version constraint to `~> 1.2.0`?

**Comment by darron** [comment]
Hey @miketheman - remember when that happened to us? I can't remember some of the backstory - but am sure you do.

**Comment by miketheman** [comment]
@hydrant25 That's a great question.

Chef Handler 1.2.0 [broke backwards compat](https://github.com/chef-cookbooks/chef_handler/blob/master/CHANGELOG.md#v120-2015-06-25) [without a major bump](https://github.com/chef-cookbooks/chef_handler/issues/34) - this caused some hellfire to rain for a while when we tried to debug it internally.

I suspect that we'd be "ok" to remove the constraint from this cookbook, but haven't been able to truly test it, since we (and many users of this cookbook) are still on Chef 11.

I think the reasoning that you're getting datadog 0.1.2 is because that was the last version of this cookbook (oh, the early, optimistic days) where we allowed "anything greater than...", so the depsolver is getting that in conjunction with the chef_handler cookbook.

My understanding is that if you reordered your Berksfile to place `datadog` cookbook before the `chef_handler` cookbook,  the resolution would retrieve the chef_handler 1.1.9 cookbook without any issue.

**Comment by hydrant25** [comment]
Thanks for the quick response, @miketheman! I did pull the constraint in my local fork and ran `kitchen test`. Looks like I ended up hitting `Timeout::Error` on starting `service[datadog-agent]` on Windows 2012r2-11186. I don't know/think that's related to the chef_handler version though.

At any rate, I did solve this in my `Berksfile` by explicitly asking for `cookbook 'datadog', version: '~> 2.2.0'`.
