### ISSUE TITLE
HTTP check creating tags with a space after the colon

### ISSUE THREAD

**Issue by truthbk** [DataDog/chef-datadog#279]
Reported by a customer:

"I noticed that when I updated the version of my cookbook, my tests failed, because the tag format changed from 'environment:production' to 'environment: production'."

This will in turn cause the check to fail due to how the YAML is parsed.

**Comment by miketheman** [comment]
The HTTP Check renders whatever is put into the data hash.
See https://github.com/DataDog/chef-datadog/blob/master/recipes/http_check.rb and  https://github.com/DataDog/chef-datadog/blob/master/templates/default/http_check.yaml.erb

So it seems like if in your `tags` element of your hash, you have:
```ruby
...
'tags' => [
  'environment: production'
]
```
The resulting template will contain `'environment: production'` and lead to unhappy yaml, because tthen it's an Object instead of a String.

Is there any more details that we can use to try and track this down?
The check and template do not appear to have ever changed since [released originally in v2.1.0](https://github.com/DataDog/chef-datadog/releases/tag/v2.1.0).

**Comment by olivielpeau** [comment]
Closing since this doesn't look related to the cookbook _per se_

@truthbk Feel free to re-open this issue if you have more info ;)
