### ISSUE TITLE
chef-handler locked at 1.1.0

### ISSUE THREAD

**Issue by mfischer-zd** [DataDog/chef-datadog#318]
Please relax the chef-handler cookbook restriction so that 1.4.0 can be used.

**Comment by olivielpeau** [comment]
Hi @mfischer-zd, the restriction on `chef-handler` is being discussed in #291.

We need to make sure that there wouldn't be adverse effects (in terms of compatibility especially) if we relaxed the condition.

I'm going to close this issue since it's a duplicate, but feel free to react on #291, thanks.
