### ISSUE TITLE
Attribute for version of datadog-agent to install is the same for Linux and Windows install packages

### ISSUE THREAD

**Issue by mlcooper** [DataDog/chef-datadog#366]
The attribute for version of the datadog-agent to be installed is the same for Linux and Windows install packages, and the problem with that is that the version number format of these packages does not match.  For example, the latest package for windows is `ddagent-cli-5.9.0.msi` and the latest for linux is `datadog-agent-5.9.0-1.x86_64.rpm`.  Linux has a `-1` and Windows does not (as is standard).

So if we were to pin a version with `node['datadog']['agent_version']` at `'5.9.0-1'` it would work for Linux, not Windows, and vice versa if we pinned it to `'5.9.0'`.  If we want to use the same attribute we have to assign the proper value of that attribute based on the platform of the node in a wrapper recipe; we couldn't just use a role/chef_environment since one platform or the other wouldn't like the value of the version.

The easiest thing might be to have
```
default['datadog']['linux_agent_version']
default['datadog']['win_agent_version']
```
and then you can set each of these separately.

**Comment by olivielpeau** [comment]
Hi @mlcooper and thanks for your detailed feedback!

The versioning is actually even more different between platforms since the deb packages include the epoch in their versions, e.g. `'1:5.9.0-1'`.

Using 3 different attributes sounds reasonable to me as long as the cookbook falls back to the "global" `node[datadog][agent_version]` attribute when they're not set.

Feel free to open a PR implementing this ; I'm putting this in triage so that we take care of it at some point if you can't. Thanks again!

**Comment by mlcooper** [comment]
@olivielpeau PR https://github.com/DataDog/chef-datadog/pull/368 has been opened for this issue.
