### ISSUE TITLE
Docker agent in 6.x

### ISSUE THREAD

**Issue by inductor** [DataDog/chef-datadog#605]
Hello, I'm confused with the doc for Docker agent.

According to https://docs.datadoghq.com/integrations/docker_daemon/#agent-v6, [docker_daemon](https://github.com/DataDog/chef-datadog/blob/master/recipes/docker_daemon.rb) is deprecated and I should use [docker](https://github.com/DataDog/chef-datadog/blob/master/recipes/docker.rb) instead, but the comment in the docker.rb says it is also deprecated in 5.x which sounds even older than docker_daemon. What should I use to get docker metrics?

**Comment by olivielpeau** [comment]
Hi @inductor, since you're using v6 of the Agent you should use the `docker` recipe.

The inline doc in the recipe is a bit misleading, but as described in the docs you linked to (https://docs.datadoghq.com/integrations/docker_daemon/#agent-v6), you should use `docker`.

We'll update the inline docs so they're clearer, thanks for bringing this up

**Comment by inductor** [comment]
Hey @olivielpeau,

Thanks for the answer! I will have a look on the docker recipe then :)

As for the doc, is `docker` actually "deprecated" as it says for v5 and previous versions, or it is not right information?

**Comment by olivielpeau** [comment]
Great, let us know how that goes!

The information is actually correct: the `docker` check in v5 is indeed deprecated, but it was fully rewritten in v6, so for v6 Agents the `docker` check is the one that should be used.
