### ISSUE TITLE
Support for UPSC

### ISSUE THREAD

**Issue by fatbasstard** [DataDog/chef-datadog#835]
Hi,

Just found out abut the UPSC integration, can this be added?

Documentation:

* https://docs.datadoghq.com/integrations/upsc/

**Comment by albertvaka** [comment]
Hi!

Some integrations don't have specific recipes, but you can still configure them using the `datadog_monitor` resource. In this case, since UPSC is a community integration that doesn't come packaged with the Agent, you also need to use the `datadog_integration` resource to install it. A recipe to install and enable the UPSC integration would look something like this:

```
include_recipe '::dd-agent'

# Install UPSC integration
datadog_integration 'datadog-upsc' do
  action      :install
  version     '1.0.0'
  third_party true
end

# Configure UPSC integration
datadog_monitor 'upsc' do
  action                   :add
  use_integration_template true
  instances                [{'ups': 'all'}]
  notifies                 :restart, 'service[datadog-agent]'
end
```

**Comment by fatbasstard** [comment]
Hi @albertvaka ,

Sorry for the late reply, but I can confirm the `datadog_integration` indeed works. Got `datadog-upsc` integration working and metrics are flowing in! 🎉
